apiVersion: v1
kind: Pod
spec:
  serviceAccountName: default
  hostAliases:
  - ip: "127.0.0.1"
    hostnames:
    - "kubernetes"
  containers:
  - name: tool-rosie
    resources:
      requests:
        cpu: "100m"
        memory: 500Mi
    image: gcr.io/latamxp-infrastructure/tool-rosie-v2:2.37.1
    imagePullPolicy: Always
    command:
      - cat
    tty: true